name: Build Zed Nightly

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour at the start of the hour
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: zed-industries/zed
          ref: main

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-wasi

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: zed-release
          path: target/release/zed.exe

      # Inno Setup section
      - name: Install Inno Setup
        run: |
          choco install innosetup --yes
          choco list --local-only innosetup

      - name: Find Inno Setup Path
        id: inno_path
        run: |
          echo "INNO_PATH=$(where ISCC.exe)" >> $GITHUB_ENV

      - name: Extract version from GitHub tag
        id: extract_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build setup.exe with Inno Setup
        run: |
          ${{ env.INNO_PATH }} zed-installer.iss /DVersion=${{ env.RELEASE_VERSION }}
        shell: cmd

      - name: Archive setup.exe
        uses: actions/upload-artifact@v4
        with:
          name: zed-setup
          path: setup.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: zed-setup
          path: zed-setup

      - name: Get the current date and time
        id: date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d%H')" >> $GITHUB_ENV

      - name: Zip the release artifact
        run: zip -r zed-windows.zip zed-setup/*

      - name: Upload release build artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.RELEASE_VERSION }}
          draft: false
          make_latest: true
          files: zed-windows.zip
